namespace: platform

backend:
  image: yourdockerhub/store-platform-backend:latest
  replicas: 1
  port: 8000
  secretName: platform-backend-secret
  existingSecret: ""
  secretKey: DATABASE_URL
  database:
    host: platform-postgres
    port: 5432
  env:
    HELM_CHART_PATH: /app/charts/woocommerce
    LOCAL_DOMAIN: localtest.me
    WORKER_MAX_CONCURRENCY: "2"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 700m
      memory: 1Gi

dashboard:
  image: yourdockerhub/store-platform-dashboard:latest
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

postgres:
  image: postgres:16-alpine
  secretName: platform-postgres-secret
  existingSecret: ""
  storageSize: 10Gi
  database: platform
  username: postgres
  password: ""

ingress:
  enabled: true
  className: traefik
  dashboardHost: platform.localtest.me
  backendHost: ""

rbac:
  create: true

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001
