{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: platform-provisioner
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: platform-provisioner-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
