{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "woocommerce.fullname" . }}-limitrange
spec:
  limits:
    - type: Container
      default:
{{ toYaml .Values.limitRange.default | indent 8 }}
      defaultRequest:
{{ toYaml .Values.limitRange.defaultRequest | indent 8 }}
{{- end }}
